Preview services
softitlanmx/softi-shop-services pull request #1
Opened 2023-10-27 15:50 UTC by AbrahamCoco

2023-10-27 18:04 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/endpoint/CarritoEndpoint.java
>  @RequestMapping("Carrito")
Tratemos de mantener homologado el tema del idioma, en general se usa ingles para nombrar métodos, rutas, variables, etc. Si lo hacen por el tema de quela bd tiene el nombre de las tablas en español habría que cambiar también eso para tenerlo en sincronía.

2023-10-27 18:05 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/endpoint/CarritoEndpoint.java
> +import org.springframework.web.bind.annotation.*;
En cuanto a importaciones se suele poner el método o constante especificas que se importan para no tener carga de más al traer todo lo que contiene la librería.

2023-10-27 18:05 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/endpoint/ProductoEndpoint.java
> +import org.springframework.web.bind.annotation.*;
En cuanto a importaciones se suele poner el método o constante especificas que se importan para no tener carga de más al traer todo lo que contiene la librería.

2023-10-27 18:06 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/endpoint/ProductoEndpoint.java
> +    @GetMapping("/HolaMundo")
Por favor borrar este tipo de pruebas al momento de mandar cambios

2023-10-27 18:08 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/model/CarritoBuilder.java
> +        if (carritoVO.getProducto() != null){
Esto de las validaciones se debe trabajar desde el ServiceImpl y aqui ya solo es que le lleguen los datos, pues en este caso en especifico si se debe tener tanto al usuario como a los productos a guardar en el carrito

2023-10-27 18:10 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/model/CarritoDTO.java
> +    private Long idUsuario;
Hay que tener cuidado con el tema del tipo Long ya que es solo para, como su nombre indica, valores grandes. Si necesecita un valor entero usar Float, aunque en este caso es un id así que es mejor usar un Int

2023-10-27 18:12 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/model/CarritoVO.java
> +    @Column(unique = true, nullable = false, name = "id_Carrito")
Si cambiaron la notación de camelCase a snake_case seguir la parte de poner en minúscula todos los terminos

2023-10-27 18:19 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/model/ProductoDTO.java
> +    @JsonProperty("Nombre")
La anotación JsonProperty para hacer que coincidan tanto el nombre de la tabla como el de Java, pero no es necesario ponerlo en todos los campos, además puedes usar la otra anotación para estos casos que es @ColumnName

2023-10-30 15:20 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/model/ProductoVO.java
> +    @NamedQuery(name = "ProductoVO.findAllProductos", query = "SELECT c from ProductoVO c"),
El findAll ya viene incluido dentro del JPA de Spring boot, si no mal recuerdo se llama findAll, en todo caso los namedQueries suelen para traer cosas en especifico como traer datos en un rango o por ejemplo si el status es 1, etc

2023-10-30 15:21 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/model/ProductoVO.java
>      private Long idProducto;
Lo mismo de los tipos de dato

2023-10-30 15:22 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/model/ProductoVO.java
>      private Long idCategoria;
La categoria si ya estan haciendo cambios en la bd puede hacer que traiga el objeto CategoriaVO si la relacionan con llave foranea

2023-10-30 15:24 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/other/DuplicateUserException.java
> +public class DuplicateUserException extends RuntimeException{
Antes de agregar nuevos métodos para excepciones verificar si hay algo parecido en Utils, ya que aquí solo se cambia el nombre del método y recibe el mensaje

2023-10-30 15:24 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/other/ResourceNotFoundException.java
> +    public ResourceNotFoundException(String message) {
mismo de las excepciones

2023-10-30 15:25 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/repostory/CarritoRepository.java
> +    @Query("select c from CarritoVO c where c.usuario.idUsuario = :idUsuario")
Para crear querys hacerlo a nivel del modelo mediante un NamedQuery

2023-10-30 15:26 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/repostory/UserRepository.java
> +    UserVO findByCorreoAndContrasenia(@Param("correo") String correo, @Param("contrasenia") String contrasenia);
Misma situación sobre tenerlo a nivel de modelado

2023-10-30 15:26 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/repostory/UserRepository.java
> +    boolean existsByNombreAndApellidosAndCorreo(@Param("nombre") String nombre, @Param("apellidos") String apellidos, @Param("correo") String correo);
Misma situación sobre tenerlo a nivel de modelado

2023-10-30 15:33 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/service/impl/CarritoServiceImpl.java
> +                .map(CarritoBuilder::fromVO)
Lo mismo de las validaciones y el manejo de errores

2023-10-30 15:40 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/service/impl/ProductoServiceImpl.java
> +                    .collect(Collectors.toList());
Aquí si tienes try cath solo que falta el detalle del error y no mandar solo un objeto vacio xd

2023-10-30 15:44 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/service/impl/UserServiceImpl.java
> +        this.userRepository = userRepository;
con el autowired no hay que declararlo como objeto solo ponerlo como lo pusieron en producto

2023-10-30 15:47 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/service/impl/UserServiceImpl.java
> +            if (userRepository.existsByNombreAndApellidosAndCorreo(
A esto me refería con dar el detalle sobre que falló

2023-10-30 15:51 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/endpoint/CarritoEndpoint.java
> +        List<CarritoDTO> carritoDTOList = carritoService.getCarritoByIdUsuario(idUsuario);
Misma situación del manejo de errores y sobre usar el Utils

2023-10-30 15:52 UTC, ChrisRojano08 requested changes
No mano si hay revisar algunas cositas XD

2023-11-14 15:17 UTC, ChrisRojano08 commented on .gitignore
> +!**/src/main/resources/application.properties
Este archivo es importante para el sistema no hay que ignorarlo, solo quiten lo que se haya modificado antes de subir cambios

2023-11-14 15:18 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/endpoint/CarritoEndpoint.java
> +    /*@PostMapping("/createCart")
No dejar código comentado

2023-11-14 15:20 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/endpoint/UserEndpoint.java
> +        LOG.info("Login()->password: {} ", password);
Los demás comentarios, si bien seria mejor quitarlos no hay tanto problema en dejarlo, sin embargo esta parte ya son datos sensibles que no se pueden tener en los LOGs

2023-11-14 15:26 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/service/impl/UserServiceImpl.java
> +    public UserDTO createUser(UserDTO userDTO) throws AppException {
Misma situación que con createCarrito

2023-11-14 15:27 UTC, ChrisRojano08 commented on src/main/java/mx/softitlan/softiShop/service/impl/UserServiceImpl.java
> +    public UserDTO loginUser(String email, String password) throws AppException {
Misma situación del tipo de respuesta

2023-11-14 15:28 UTC, ChrisRojano08 commented on src/main/resources/scripts/DBsoftishop.sql
> +INSERT INTO `products` VALUES (1,'Dulce ajolote','uwu',6,150,'20x30','http://drive.google.com/uc?export=view&id=17HtFo908mjqp0jaR6cuZZBOpXx0CO5vW'),(2,'Bubu 14 de febrero','unu',2,200,'30x30','http:/
Si van a respaldar la db solo dejen la estructura y partes importantes del sistema, como configuraciones o urls para no guardar datos en el repositorio

2023-11-14 15:31 UTC, ChrisRojano08 requested changes
Revisar comentarios

2023-11-15 00:54 UTC, AbrahamCoco commented
Quite que retorne los objetos y solo mande las respuestas

2023-11-15 15:23 UTC, ChrisRojano08 approved these changes

2023-11-15 15:27 UTC, merged